# Generated by Django 5.1.2 on 2024-11-19 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('status', models.SmallIntegerField(choices=[(1, 'Published'), (2, 'Draft'), (3, 'Ready'), (4, 'Aggregated')], default=2)),
                ('year_level', models.SmallIntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year'), (5, 'Fifth Year'), (6, 'Graduated')], default=1)),
                ('semester', models.SmallIntegerField(choices=[(1, '1st Term'), (2, '2nd Term')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_level', models.SmallIntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year'), (5, 'Fifth Year'), (6, 'Graduated')], default=1)),
                ('semester', models.CharField(max_length=10)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_score', models.DecimalField(db_default=100, decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='GradeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_score', models.DecimalField(db_default=100, decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='GradeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type', models.SmallIntegerField(choices=[(1, 'Quiz'), (2, 'Non-quiz')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration_years', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'Major',
                'verbose_name_plural': 'Majors',
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(help_text='Enter the starting year (e.g., 2023)')),
                ('end_year', models.IntegerField(help_text='Enter the ending year (e.g., 2024)')),
                ('status', models.SmallIntegerField(choices=[(1, 'FINISHED'), (2, 'CURRENT')], default=2)),
                ('current_semester', models.SmallIntegerField(choices=[(1, '1st Term'), (2, '2nd Term')], default=1)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('start_year', 'end_year'), name='unique_academic_year')],
            },
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_assignments', to='academics.course')),
            ],
            options={
                'verbose_name': 'Course Assignment',
                'verbose_name_plural': 'Course Assignments',
            },
        ),
    ]
