# Generated by Django 5.1.2 on 2024-11-19 21:48

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassignment',
            name='student_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_assignments', to='users.studentgroup'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_courses', to='users.teacher'),
        ),
        migrations.AddField(
            model_name='grade',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='academics.course'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='users.student'),
        ),
        migrations.AddField(
            model_name='gradedetail',
            name='course_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_details', to='academics.grade'),
        ),
        migrations.AddField(
            model_name='gradetype',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_types', to='academics.course'),
        ),
        migrations.AddField(
            model_name='gradedetail',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.gradetype'),
        ),
        migrations.AddField(
            model_name='grade',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.major'),
        ),
        migrations.AddField(
            model_name='course',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.major'),
        ),
        migrations.AddConstraint(
            model_name='courseassignment',
            constraint=models.UniqueConstraint(fields=('student_group', 'course'), name='unique_student_group_course'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_lower_name_course'),
        ),
    ]
