# Generated by Django 5.1.2 on 2024-10-31 01:08

import core.constants
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0002_student_studentgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=core.constants.Semester.choices)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicyear')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.studentgroup')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.teacher')),
            ],
            options={
                'verbose_name': 'Syllabus',
                'verbose_name_plural': 'Syllabuses',
                'constraints': [models.UniqueConstraint(fields=('student_group', 'subject'), name='unique_curriculum')],
            },
        ),
    ]
