# Generated by Django 5.1.2 on 2024-10-31 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_syllabus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabus',
            old_name='term',
            new_name='semester',
        ),
    ]
