# Generated by Django 5.1.2 on 2024-10-31 22:11

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_rename_term_syllabus_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_lower_name_course'),
        ),
    ]
