# Generated by Django 5.1.2 on 2024-11-01 22:55

import core.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_course_options_course_unique_lower_name_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='current_semester',
            field=models.SmallIntegerField(choices=core.constants.Semester.choices, default=core.constants.Semester['FIRST_SEMESTER']),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Check this box if this is the current academic year'),
        ),
    ]
