# Generated by Django 5.1.2 on 2024-11-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_academicyear_current_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='is_current',
        ),
        migrations.AddField(
            model_name='academicyear',
            name='status',
            field=models.SmallIntegerField(default=3, verbose_name=[(1, 'FINISHED'), (2, 'CURRENT'), (3, 'Upcoming')]),
        ),
    ]
