# Generated by Django 5.1.2 on 2024-11-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_academicyear_status'),
        ('users', '0010_alter_user_role'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='syllabus',
            name='unique_curriculum',
        ),
        migrations.RenameField(
            model_name='syllabus',
            old_name='subject',
            new_name='course',
        ),
        migrations.AddConstraint(
            model_name='syllabus',
            constraint=models.UniqueConstraint(fields=('student_group', 'course'), name='unique_curriculum'),
        ),
    ]
