# Generated by Django 5.1.2 on 2024-11-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_remove_syllabus_unique_curriculum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='quiz_count',
            field=models.IntegerField(db_default=1),
        ),
    ]
