# Generated by Django 5.1.2 on 2024-11-07 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_syllabus_quiz_count'),
        ('users', '0010_alter_user_role'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='syllabus',
            name='unique_curriculum',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='quiz_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='student_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.studentgroup'),
        ),
        migrations.AddConstraint(
            model_name='syllabus',
            constraint=models.UniqueConstraint(fields=('student_group', 'course', 'academic_year'), name='unique_curriculum'),
        ),
    ]
