# Generated by Django 5.1.2 on 2024-11-08 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_remove_syllabus_unique_curriculum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='quiz_count',
        ),
    ]
