# Generated by Django 5.1.2 on 2024-10-19 00:05

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('users', '0002_teacher_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('time', models.IntegerField(help_text='duration of the quiz in minutes')),
                ('number_of_questions', models.IntegerField()),
                ('required_score_to_pass', models.IntegerField(help_text='required score in %')),
                ('is_randomized', models.BooleanField(default=False)),
                ('easy_questions_count', models.IntegerField(default=0)),
                ('medium_questions_count', models.IntegerField(default=0)),
                ('hard_questions_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', taggit.managers.TaggableManager(help_text='Add tags for categories like subject, grade, etc.', through='common.CategorizedTaggedItem', to='common.CategorizedTag', verbose_name='Tags')),
                ('teachers_in_charge', models.ManyToManyField(related_name='quizzes_in_charge', to='users.teacher')),
            ],
        ),
    ]
