# Generated by Django 5.1.2 on 2024-11-19 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField()),
                ('password', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(1, 'Live'), (2, 'Upcoming'), (3, 'Ready'), (4, 'Finished')], default=2)),
            ],
            options={
                'verbose_name': 'QuizSession',
                'verbose_name_plural': 'QuizSessions',
            },
        ),
        migrations.CreateModel(
            name='QuizStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Pass'), (2, 'Fail'), (3, 'Absent'), (4, 'Upcoming')], db_default=4)),
            ],
        ),
        migrations.CreateModel(
            name='QuizStudentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_options', to='quiz.question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('time', models.IntegerField(default=90)),
                ('number_of_questions', models.IntegerField(blank=True, default=20)),
                ('required_score_to_pass', models.IntegerField(default=50)),
                ('is_randomized', models.BooleanField(default=False)),
                ('status', models.SmallIntegerField(choices=[(1, 'Published'), (2, 'Draft'), (3, 'Ready to Live'), (4, 'Live'), (5, 'Finished')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(related_name='quizzes', to='academics.courseassignment')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='quiz.quiz'),
        ),
    ]
