# Generated by Django 5.1.2 on 2024-11-19 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('quiz', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='additional_students',
            field=models.ManyToManyField(to='users.student'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='excluded_students',
            field=models.ManyToManyField(related_name='sessions_excluded', to='users.student'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quiz.quizsession'),
        ),
        migrations.AddField(
            model_name='quizstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AddField(
            model_name='quizstudent',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.courseassignment'),
        ),
        migrations.AddField(
            model_name='quizstudentquestion',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.questionoption'),
        ),
        migrations.AddField(
            model_name='quizstudentquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
        migrations.AddField(
            model_name='quizstudentquestion',
            name='quiz_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizstudent'),
        ),
    ]
