# Generated by Django 5.1.2 on 2024-10-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='teachers_in_charge',
            field=models.ManyToManyField(related_name='quizzes_in_charge', to='users.teacher'),
        ),
    ]
