# Generated by Django 5.1.2 on 2024-11-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_course_options_course_unique_lower_name_course'),
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='teachers_in_charge',
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_for',
            field=models.ManyToManyField(related_name='quizzes_for_this_syllabus', to='academics.syllabus'),
        ),
    ]
