# Generated by Django 5.1.2 on 2024-11-20 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='courses',
            new_name='course_assignments',
        ),
    ]
