# Generated by Django 5.1.2 on 2024-11-01 20:25

import core.constants
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_quiz_teachers_in_charge_quiz_quiz_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('options', models.JSONField()),
                ('answer', models.SmallIntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('question_difficulty', models.SmallIntegerField(choices=core.constants.QuestionDifficulty.choices, default=1)),
                ('question_type', models.IntegerField(choices=core.constants.QuestionType.choices, default=2)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='quiz.quiz')),
            ],
        ),
    ]
