# Generated by Django 5.1.2 on 2024-11-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='easy_questions_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='hard_questions_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='medium_questions_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(default=90, help_text='duration of the quiz in minutes'),
        ),
    ]
