# Generated by Django 5.1.2 on 2024-11-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_quiz_easy_questions_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='number_of_questions',
            field=models.IntegerField(blank=True),
        ),
    ]
