# Generated by Django 5.1.2 on 2024-11-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_quiz_number_of_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the quiz. If not provided, it will be generated based on the syllabus.', max_length=120),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='number_of_questions',
            field=models.IntegerField(blank=True, default=20),
        ),
    ]
