# Generated by Django 5.1.2 on 2024-11-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_quiz_name_alter_quiz_number_of_questions'),
        ('users', '0010_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('password', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(1, 'Live'), (2, 'Upcoming'), (3, 'Finished')], default=2)),
                ('students', models.ManyToManyField(related_name='quiz_sessions', to='users.student')),
            ],
            options={
                'verbose_name': 'QuizSession',
                'verbose_name_plural': 'QuizSessions',
            },
        ),
    ]
