# Generated by Django 5.1.2 on 2024-11-03 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_quizsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quiz.quizsession'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Published'), (2, 'Draft'), (3, 'Ready to Live'), (4, 'Live'), (5, 'Finished')], default=2),
        ),
    ]
