# Generated by Django 5.1.2 on 2024-11-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_quiz_quiz_session_quiz_status'),
        ('users', '0010_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsession',
            name='students',
        ),
        migrations.AddField(
            model_name='quizsession',
            name='allowed_groups',
            field=models.ManyToManyField(related_name='quiz_sessions', to='users.studentgroup'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='excluded_students',
            field=models.ManyToManyField(related_name='sessions_excluded', to='users.student'),
        ),
    ]
