# Generated by Django 5.1.2 on 2024-11-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_syllabus_quiz_count'),
        ('quiz', '0011_alter_quiz_options_remove_quiz_quiz_for_quizsyllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_for',
            field=models.ManyToManyField(related_name='quizzes_for_this_syllabus', through='quiz.QuizSyllabus', to='academics.syllabus'),
        ),
        migrations.AddField(
            model_name='quizsyllabus',
            name='quiz_number',
            field=models.IntegerField(default=1),
        ),
    ]
