# Generated by Django 5.1.2 on 2024-11-04 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_quiz_quiz_for_quizsyllabus_quiz_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsession',
            name='allowed_groups',
        ),
    ]
