# Generated by Django 5.1.2 on 2024-11-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_remove_quizsession_allowed_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='required_score_to_pass',
            field=models.IntegerField(db_default=50, help_text='required score in %'),
        ),
    ]
