# Generated by Django 5.1.2 on 2024-11-05 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_syllabus_quiz_count'),
        ('quiz', '0014_alter_quiz_required_score_to_pass'),
        ('users', '0010_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='name',
            new_name='title',
        ),
        migrations.CreateModel(
            name='QuizStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Pass'), (2, 'Fail'), (3, 'Absent'), (4, 'Upcoming')], db_default=4)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.syllabus')),
            ],
        ),
        migrations.CreateModel(
            name='QuizStudentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.SmallIntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('quiz_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizstudent')),
            ],
        ),
    ]
