# Generated by Django 5.1.2 on 2024-11-05 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_remove_question_options_questionoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizstudentquestion',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.questionoption'),
        ),
    ]
