# Generated by Django 5.1.2 on 2024-11-05 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_alter_quizstudentquestion_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_answer', to='quiz.questionoption'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='status',
            field=models.IntegerField(choices=[(1, 'Live'), (2, 'Upcoming'), (3, 'Ready'), (4, 'Finished')], default=2),
        ),
    ]
