# Generated by Django 5.1.2 on 2024-11-05 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_alter_question_answer_alter_quizsession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_answer', to='quiz.questionoption'),
        ),
    ]
