# Generated by Django 5.1.2 on 2024-11-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_alter_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(choices=[(1, 'Multiple Choice'), (2, 'True or False')], default=1),
        ),
    ]
