# Generated by Django 5.1.2 on 2024-11-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_alter_question_question_type'),
        ('users', '0010_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsyllabus',
            name='quiz_number',
        ),
        migrations.AddField(
            model_name='quizsession',
            name='additional_students',
            field=models.ManyToManyField(to='users.student'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='required_score_to_pass',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
