# Generated by Django 5.1.2 on 2024-11-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_remove_syllabus_quiz_count'),
        ('quiz', '0021_remove_quizsyllabus_quiz_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_for',
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_for',
            field=models.ManyToManyField(related_name='quizzes_for_this_syllabus', to='academics.syllabus'),
        ),
        migrations.DeleteModel(
            name='QuizSyllabus',
        ),
    ]
