# Generated by Django 5.1.2 on 2024-11-09 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_alter_quiz_quiz_for_delete_quizsyllabus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_difficulty',
            new_name='difficulty_level',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
    ]
