# Generated by Django 5.1.2 on 2024-11-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_rename_question_difficulty_question_difficulty_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.AddField(
            model_name='questionoption',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
