# Generated by Django 5.1.2 on 2024-11-12 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_remove_question_type_questionoption_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='easy_questions_count',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='hard_questions_count',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='medium_questions_count',
        ),
    ]
