# Generated by Django 5.1.2 on 2024-10-19 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorizedtag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='tagcategory',
            options={'verbose_name': 'Tag Category', 'verbose_name_plural': 'Tag Categories'},
        ),
        migrations.AddConstraint(
            model_name='categorizedtag',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_tag_name_category'),
        ),
        migrations.AddConstraint(
            model_name='tagcategory',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_tag_category_name'),
        ),
    ]
