# Generated by Django 5.1.2 on 2024-10-31 01:06

import core.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_level', models.CharField(choices=core.constants.YearLevel.choices, max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('education_type', models.CharField(choices=core.constants.EducationType.choices, max_length=100)),
            ],
        ),
    ]
