# Generated by Django 5.1.2 on 2024-10-31 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_rename_term_syllabus_semester'),
        ('users', '0003_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.major'),
        ),
    ]
