# Generated by Django 5.1.2 on 2024-10-31 18:35

import core.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_studentgroup_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='year_level',
            field=models.IntegerField(choices=core.constants.YearLevel.choices),
        ),
    ]
