# Generated by Django 5.1.2 on 2024-10-31 18:36

import core.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_studentgroup_year_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='education_type',
            field=models.IntegerField(choices=core.constants.EducationType.choices),
        ),
    ]
