# Generated by Django 5.1.2 on 2024-11-09 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_remove_syllabus_quiz_count'),
        ('users', '0010_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroup',
            name='name',
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='number',
            field=models.SmallIntegerField(choices=[(1, 'Group 1'), (2, 'Group 2'), (3, 'Group 3'), (4, 'Group 4'), (5, 'Group 5')], default=1),
        ),
    ]
